# Site settings
title: Valentina Ramirez
description: Welcome to my personal website!
baseurl: ""
url: "https:/valramirezvasquez.github.io"
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Navigation menu
nav_menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Blog
    url: /blog

# Social media links
social:
  - title: Twitter
    icon: fab fa-twitter
    url: https://twitter.com/example
  - title: GitHub
    icon: fab fa-github
    url: https://github.com/example

# Default pagination settings
paginate: 10
paginate_path: "/page/:num/"



